openapi: 3.0.3
info:
  title: part1
  description: part1
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Patients
    description: Endpoints for managing patients
  - name: Doctors
    description: Endpoints for managing doctors
  - name: Appointments
    description: Endpoints for managing appointments
  - name: Medical Records
    description: Endpoints for managing medical records
components:
  schemas:
    Patient:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        address:
          type: string
    Doctor:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        specialisation:
          type: string
        email:
          type: string
        phone_number:
          type: string
    Appointment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        appointment_date:
          type: string
          format: date-time
        status:
          type: string
        notes:
          type: string
    MedicalRecord:
      type: object
      properties:
        id:
          type: integer
          format: int64
        record_date:
          type: string
          format: date-time
        diagnosis:
          type: string
        treatment:
          type: string
        notes:
          type: string
paths:
  /patients:
    get:
      tags:
        - Patients
      summary: List all patients
      responses:
        '200':
          description: List of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
        '404':
          description: No patients found
    post:
      tags:
        - Patients
      summary: Create a new patient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '201':
          description: Patient created
        '400':
          description: Invalid patient data
  /patients/{id}:
    get:
      tags:
        - Patients
      summary: Get patient by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Patient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Patient not found
    put:
      tags:
        - Patients
      summary: Update patient by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: Patient updated
        '404':
          description: Patient not found
    delete:
      tags:
        - Patients
      summary: Delete patient by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Patient deleted
        '404':
          description: Patient not found
  /patients/{id}/appointments:
    get:
      tags:
        - Patients
      summary: Get appointments for a patient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '404':
          description: Patient not found
  /patients/{id}/medical-records:
    get:
      tags:
        - Patients
      summary: Get medical records for a patient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of medical records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicalRecord'
        '404':
          description: Patient not found
  /doctors:
    get:
      tags:
        - Doctors
      summary: List all doctors
      responses:
        '200':
          description: List of doctors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doctor'
        '404':
          description: No doctors found
  /doctors/{id}:
    get:
      tags:
        - Doctors
      summary: Get doctor by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Doctor found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
        '404':
          description: Doctor not found
    put:
      tags:
        - Doctors
      summary: Update doctor by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Doctor'
      responses:
        '200':
          description: Doctor updated
        '404':
          description: Doctor not found
    delete:
      tags:
        - Doctors
      summary: Delete doctor by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Doctor deleted
        '404':
          description: Doctor not found
    post:
      tags:
        - Doctors
      summary: Create a new doctor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Doctor'
      responses:
        '201':
          description: Doctor created
        '400':
          description: Invalid doctor data
  /doctors/{id}/appointments:
    get:
      tags:
        - Doctors
      summary: Get appointments for a doctor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '404':
          description: Doctor not found
  /appointments:
    get:
      tags:
        - Appointments
      summary: List all appointments
      responses:
        '200':
          description: List of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '404':
          description: No appointments found
    post:
      tags:
        - Appointments
      summary: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created
        '400':
          description: Invalid appointment data
  /appointments/{id}:
    get:
      tags:
        - Appointments
      summary: Get appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Appointment found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: Appointment not found
    put:
      tags:
        - Appointments
      summary: Update appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment updated
        '404':
          description: Appointment not found
    delete:
      tags:
        - Appointments
      summary: Delete appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Appointment deleted
        '404':
          description: Appointment not found
  /appointments/{id}/medical-record:
    get:
      tags:
        - Appointments
      summary: Get medical records for an appointment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of medical records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicalRecord'
        '404':
          description: Appointment not found
  /medical-records:
    post:
      tags:
        - Medical Records
      summary: Create a new medical record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicalRecord'
      responses:
        '201':
          description: Medical record created
        '400':
          description: Invalid medical record data
